wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1649778120
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 15
      4: 3.8.5
      5: 0.12.14
      8:
      - 5
